apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster
  namespace: {{ .Values.namespace }}
spec:
  rayVersion: "2.48"
  
  headGroupSpec:
    replicas: 1
    serviceAccount: {{ .Values.headServiceAccount }}
    rayStartParams:
      dashboard-host: "0.0.0.0"
      include-dashboard: "true"
    template:
      spec:
        containers:
          - name: ray-head
            image: 948959680124.dkr.ecr.us-west-2.amazonaws.com/protoplast/head:latest
            env:
              - name: AWS_REGION
                value: {{ .Values.awsRegion }}
              - name: AWS_ACCOUNT_ID
                value: {{ .Values.awsAccountId | quote }}
              - name: S3_BUCKET
                value: {{ .Values.s3Bucket }}
        nodeSelector:
          gpu: "false"
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "cpu"
            effect: "NoSchedule"

  workerGroupSpecs:
    - groupName: cpu-workers
      replicas: 0
      template:
        spec:
          serviceAccountName: {{ .Values.workerServiceAccount }}
          containers:
            - name: ray-worker
              image: 948959680124.dkr.ecr.us-west-2.amazonaws.com/protoplast/head:latest
              env:
                - name: AWS_REGION
                  value: {{ .Values.awsRegion }}
                - name: AWS_ACCOUNT_ID
                  value: {{ .Values.awsAccountId | quote }}
                - name: S3_BUCKET
                  value: {{ .Values.s3Bucket }}
          nodeSelector:
            gpu: "false"
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "cpu"
              effect: "NoSchedule"

    - groupName: gpu-workers
      replicas: 0
      template:
        spec:
          serviceAccountName: {{ .Values.workerServiceAccount }}
          containers:
            - name: ray-worker
              image: 948959680124.dkr.ecr.us-west-2.amazonaws.com/protoplast/worker:latest
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              env:
                - name: AWS_REGION
                  value: {{ .Values.awsRegion }}
                - name: AWS_ACCOUNT_ID
                  value: {{ .Values.awsAccountId | quote }}
                - name: S3_BUCKET
                  value: {{ .Values.s3Bucket }}
          nodeSelector:
            gpu: "true"
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "gpu"
              effect: "NoSchedule"
